import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link href="/"></Link>
            <Link href="/about"></Link>
            <Link href="/team"></Link>
            <Link href="/foods"></Link>
            <Link href="/location"></Link>
            <Link href="/poutry"></Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}